# Generated by Django 4.0.4 on 2022-07-08 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member', '0002_alter_socio_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='socio',
            field=models.OneToOneField(default='null', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Sócio'),
        ),
    ]
