# Generated by Django 4.0.4 on 2022-07-12 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_socio_socio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socio',
            old_name='socio',
            new_name='usuario',
        ),
    ]
