# Generated by Django 4.0.4 on 2022-05-31 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aeronave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=6)),
                ('valor_hora', models.FloatField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_instrutor', models.CharField(max_length=30)),
                ('canac_instrutor', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Voo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horimetro_inicial', models.CharField(max_length=6)),
                ('horimetro_final', models.CharField(max_length=6)),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('mostrar', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('Instrução', 'Instrução'), ('Privado', 'Privado')], default='Instrução', max_length=10)),
                ('aeronave', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='flights.aeronave')),
                ('instrutor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='flights.instrutor')),
                ('piloto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voo',
            },
        ),
    ]
