# Generated by Django 4.0.4 on 2022-07-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_alter_instrutor_options_financeiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='voo',
            name='valor_voo_total',
            field=models.FloatField(null=True),
        ),
    ]
