# Generated by Django 4.0.4 on 2022-07-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_voo_valor_voo_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voo',
            name='valor_voo_total',
            field=models.FloatField(editable=False, null=True),
        ),
    ]
